# Generated by Django 2.0.4 on 2018-04-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_specialist', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(to='main.Skill', verbose_name='list of skills')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(to='main.Skill', verbose_name='question skills'),
        ),
        migrations.AddField(
            model_name='chat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='main.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.User'),
        ),
    ]
